### ISSUE TITLE
Tail call optimization still isn't quite working

### ISSUE THREAD

**Issue by jbarrmetro** [jasonsbarr/wanda#12]
I've implemented TCO via a trampoline and it still isn't quite working. It's an improvement from about 1500 calls of this function without it:

```clojure
(def fact (n a)
  (if (= 1 n)
    a
    (fact (- n 1) (* n a))))
```

to about 7000 recursive calls with it, but it's still not giving me infinite tail recursion. I know the trampoline isn't the problem, because when I use it with a JavaScript function I do in fact get infinite tail recursion, so something somewhere in the language has to be putting something on the call stack that isn't getting completely popped off and it's building up for long enough that it finally causes the stack to blow.

I have no idea what's causing it, and if someone can find it I would gladly Venmo them $10 for a drink on me.

**Comment by jasonsbarr** [comment]
Fixed as of about 9 months ago.
